cmake -S C:\work\ldk ^
  -B C:\work\ldk\demo\solution\ ^
  -G "Visual Studio 18 2026" ^
  -A x64 ^
  -DOPTION_LDK_USE_PREBUILT=ON ^
  -DOPTION_LDK_PREBUILT_DIR=C:\work\ldk ^
  -DOPTION_BUILD_GAME=ON ^
  -DOPTION_BUILD_EDITOR=OFF ^
  -DOPTION_BUILD_GAME_LAUNCHER=OFF ^
  -DOPTION_BUILD_TESTS=OFF ^
  -DOPTION_GAME_DIR=C:\work\ldk\demo
