name: CMake Multi-Preset Build 


on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch: 

jobs:  
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        preset: [release, relwithdebinfo]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install CMake and Ninja on Windows (if Ninja is used as the generator)
    - name: Install dependencies
      run: |
        choco install ninja --no-progress  # Ninja is optional based on your generator

    # Configure the project using CMakePresets.json
    - name: Configure with CMake Preset
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -startdir=none -arch=x64 -host_arch=x64
        cmake --preset ${{ matrix.preset }}

    # Build the project using the configured preset
    - name: Build using CMake Preset
      run: cmake --build --preset ${{ matrix.preset }}
      
