name: CMake Multi-Preset Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        preset: [release, relwithdebinfo]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup MSBuild environment
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
            msbuild-architecture: x64
      
      - name: Install Ninja
        run: choco install ninja

      # Configure the project using CMakePresets.json
      - name: Configure with CMake Preset
        run: cmake --preset ${{ matrix.preset }} -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_C_COMPILER=cl.exe

      # Build the project using the configured preset
      - name: Build using CMake Preset
        run: cmake --build --preset ${{ matrix.preset }}
