name: CMake Multi-Preset Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        preset: [Release, RelWithDebInfo]  # Uppercase to match CMake convention

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (Ninja, if using Ninja as generator, and CMake)
      - name: Install dependencies
        run: |
          choco install ninja

      # Optionally install CMake if it's not pre-installed
      - name: Install CMake
        uses: lukka/get-cmake@v3  # Ensure CMake is installed

      # Configure the project using CMakePresets.json
      - name: Configure with CMake Preset
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -startdir=none -arch=x64 -host_arch=x64
          cmake --preset ${{ matrix.preset }}

      # Build the project using the configured preset
      - name: Build using CMake Preset
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -startdir=none -arch=x64 -host_arch=x64
          cmake --build --preset ${{ matrix.preset }}
