name: CMake Multi-Preset Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        preset: [Release, RelWithDebInfo]  # Uppercase to match CMake convention

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup MSBuild environment (this automatically configures MSBuild and VS tools)
      - name: Setup MSBuild
        uses: actions/setup-msbuild@v1

      # Optionally install CMake if it's not pre-installed
      - name: Install CMake
        uses: lukka/get-cmake@v3  # Ensure CMake is installed

      # Install Ninja (only if you are using Ninja as the generator in CMakePresets.json)
      - name: Install Ninja
        run: |
          choco install ninja

      # Configure the project using CMakePresets.json
      - name: Configure with CMake Preset
        run: cmake --preset ${{ matrix.preset }}

      # Build the project using the configured preset
      - name: Build using CMake Preset
        run: cmake --build --preset ${{ matrix.preset }}
