name: CMake Multi-Preset Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        preset: [Release, RelWithDebInfo]  # Ensure consistency with CMake preset names

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup MSBuild environment (sets up MSBuild, Visual Studio, and related tools)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1  # Correct the action name and repo

      # Install dependencies (CMake and Ninja, if needed)
      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      
      - name: Install Ninja (Optional, if you're using Ninja as the generator)
        run: |
          choco install ninja

      # Configure the project using CMakePresets.json
      - name: Configure with CMake Preset
        run: cmake --preset ${{ matrix.preset }}

      # Build the project using the configured preset
      - name: Build using CMake Preset
        run: cmake --build --preset ${{ matrix.preset }}
